
- name: Enable proxy_ajp, ssl modules, shib2
  apache2_module: name={{ item }} state=present
  with_items:
    - proxy_ajp
    - ssl
    - shib2

- name: Add apache2 user to ssl-cert group
  user: name=apache2 groups=ssl-cert

- name: Remove Default site configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Remove Index file
  file: path=/var/www/html/index.html state=absent

- name: Configure HTTPS only listen port
  copy:
    src: roles/apache2/files/ports.conf
    dest: /etc/apache2/ports.conf

- name: Install IdP Virtualhost configuration
  template:
    src: roles/apache2/templates/idp.conf
    dest: /etc/apache2/sites-available/{{ idp_fqdn }}.conf

- name: Install SP Virtualhost configuration
  template:
    src: roles/apache2/templates/sp.conf
    dest: /etc/apache2/sites-available/{{ sp_fqdn }}.conf


- name: Dirs for IdP and SP Virtualhosts
  file: name={{ item }} state=directory
  with_items:
    - /var/log/apache2/{{ idp_fqdn }}
    - /var/log/apache2/{{ sp_fqdn }}
    - /var/www/html/{{ sp_fqdn }}
    - /var/www/html/{{ sp_fqdn }}/secure
    - /var/www/html/{{ idp_fqdn }}
    - /var/www/css

- name: Install IdP Index file 
  template:
    src: roles/apache2/templates/idp-index.html
    dest: /var/www/html/{{ idp_fqdn }}/index.html

- name: Site content for {{ sp_fqdn }}
  copy:
    src: roles/apache2/files/sp.example.org/
    dest: /var/www/html/{{ sp_fqdn }}/

- name: Parse {{ sp_fqdn }} in index.html
  template:
    src: roles/apache2/files/sp.example.org/index.html
    dest: /var/www/html/{{ sp_fqdn }}/index.html

- name: Parse {{ domain }} in attributes_map.php
  template:
    src: roles/apache2/files/sp.example.org/secure/attributes_map.php
    dest: /var/www/html/{{ sp_fqdn }}/secure/attributes_map.php

- name: Remove old secure {{ sp_fqdn }} index file
  file:
    path: /var/www/html/{{ sp_fqdn }}/secure/index.html
    state: absent
    
- name: Install Bootstrap Min CSS 
  copy:
    src: roles/apache2/files/bootstrap.min.css
    dest: /var/www/css/bootstrap.min.css

- name: Enable IdP Virtualhost
  command: a2ensite {{ idp_fqdn }}.conf
  args:
    creates: /etc/apache2/sites-enabled/{{ idp_fqdn }}.conf

- name: Enable SP Virtualhost
  command: a2ensite {{ sp_fqdn }}.conf
  args:
    creates: /etc/apache2/sites-enabled/{{ sp_fqdn }}.conf

- name: Restart Apache2
  service: name=apache2 state=restarted enabled=yes

