# CLEANUPS
- name: Stop {{ tomcat_version }}
  service: name={{ tomcat_version }} state=stopped enabled=false
  when: cleanup is defined
  #~ ignore_errors: yes
 
#~ - name: Stop tomcat
  #~ service: name=tomcat state=stopped enabled=false
  #~ when: cleanup is defined
  #~ ignore_errors: yes 

- name: Uninstall {{ tomcat_version }}
  apt: name={{ tomcat_version }} state=absent purge=yes
  when: cleanup is defined
  # END CLEANUP
  
# to improve security watch this: https://www.owasp.org/index.php/Securing_tomcat

- name: Remove /etc/tomcat*
  file: path=/etc/tomcat* state=absent
  when: cleanup is defined

# END CLEANUP

- name: Install {{ tomcat_version }}
  apt: name={{ tomcat_version }} state=present

- name: /etc/{{ tomcat_version }}/server.xml with AJP, NO 8080, and no autoDeploy
  template:
    src: roles/tomcat/templates_{{ tomcat_version }}/server.xml
    dest: /etc/{{ tomcat_version }}/server.xml

- name: /etc/default/{{ tomcat_version }} with urandom and 384m heap mem
  template:
    src: roles/tomcat/templates_{{ tomcat_version }}/{{ tomcat_version }}
    dest: /etc/default/{{ tomcat_version }}

- name: Install JSTL-1.2 library
  get_url:
    url: https://repo1.maven.org/maven2/jstl/jstl/1.2/jstl-1.2.jar
    dest: /usr/share/{{ tomcat_version }}/lib

- name: Link mysql-java library
  file:
    src: /usr/share/java/mysql.jar
    dest: /usr/share/{{ tomcat_version }}/lib/mysql.jar
    state: link
  
- name: Restart {{ tomcat_version }}
  service: name={{ tomcat_version }} state=restarted enabled=yes
